/**
 * UK Food Standards Agency (FSA) 14 Major Allergens
 * Base de datos de alérgenos oficiales con ejemplos culinarios prácticos,
 * fuentes de contaminación cruzada y palabras clave para auto-detección.
 */

window.UK_ALLERGENS = [
    {
        id: 'celery',
        name_es: 'Apio',
        name_en: 'Celery',
        icon: 'spa',
        color: '#2E7D32',
        bg: '#E8F5E9',
        border: '#A5D6A7',
        whereItHides_es: 'Pastillas de caldo (Knorr, Bovril), sal de apio, sofrito clásico (mirepoix), sopas preparadas, cóctel Bloody Mary, mezclas de especias preparadas.',
        whereItHides_en: 'Stock cubes (Knorr, Bovril), celery salt, mirepoix bases, pre-made soups, Bloody Mary cocktails, spice blends.',
        contaminationRisks_es: 'Tablas de picar donde se corta apio para caldos, cuchillos de chef no higienizados entre preparaciones, batidoras de purés.',
        contaminationRisks_en: 'Chopping boards used for mirepoix, unwashed chef knives between tasks, shared soup blenders.',
        keywords: ['apio', 'celery', 'mirepoix', 'sal de apio', 'celery salt', 'knorr', 'bovril', 'cubito de caldo']
    },
    {
        id: 'gluten',
        name_es: 'Gluten (Cereales)',
        name_en: 'Gluten',
        icon: 'bakery_dining',
        color: '#D97706',
        bg: '#FEF3C7',
        border: '#FDE68A',
        whereItHides_es: 'Harina de trigo, pan rallado, pasta, cerveza, salsa de soja regular, bechamel, rebozados, galletas, salsa espesada con harina, cuscús, avena común.',
        whereItHides_en: 'Wheat flour, breadcrumbs, pasta, beer, standard soy sauce, roux/béchamel, batters, biscuits, thickened gravies, couscous, oats.',
        contaminationRisks_es: '¡El #1 en cocinas! Freidoras compartidas (freír patatas en el mismo aceite de croquetas o rebozados), tostadoras de pan, harina volátil en el aire.',
        contaminationRisks_en: '#1 in kitchens! Shared deep fat fryers (chips fried with battered fish/croquettes), toasters, airborne flour dust.',
        keywords: ['harina', 'trigo', 'gluten', 'flour', 'wheat', 'pan', 'bread', 'pasta', 'cerveza', 'beer', 'soja', 'soy sauce', 'breadcrumbs', 'pan rallado', 'bechamel', 'oats', 'avena', 'cebada', 'barley', 'centeno', 'rye', 'cuscus', 'couscous', 'hojaldre', 'pastry']
    },
    {
        id: 'crustaceans',
        name_es: 'Crustáceos',
        name_en: 'Crustaceans',
        icon: 'phishing',
        color: '#DC2626',
        bg: '#FEE2E2',
        border: '#FECACA',
        whereItHides_es: 'Gambas, langostinos, cangrejos, langosta, pasta de gambas asiática (shrimp paste en currys tailandeses), fumets de marisco.',
        whereItHides_en: 'Prawns, shrimp, crabs, lobster, langoustines, Asian shrimp paste (in Thai curries), seafood stocks.',
        contaminationRisks_es: 'Woks y sartenes de salteados que no se lavan entre platos, aceites de fritura compartidos, pinzas de parrilla.',
        contaminationRisks_en: 'Woks and sauté pans not scrubbed between orders, shared frying oils, grill tongs.',
        keywords: ['gamba', 'gambas', 'langostino', 'langostinos', 'prawn', 'prawns', 'shrimp', 'crab', 'cangrejo', 'lobster', 'langosta', 'shrimp paste', 'pasta de gamba', 'marisco']
    },
    {
        id: 'eggs',
        name_es: 'Huevos',
        name_en: 'Eggs',
        icon: 'egg',
        color: '#CA8A04',
        bg: '#FEF9C3',
        border: '#FEF08A',
        whereItHides_es: 'Mayonesa, salsa holandesa, merengues, pasta fresca al huevo, masa de tartas, barnizado de bollos/brioche con huevo, albóndigas (aglutinante).',
        whereItHides_en: 'Mayonnaise, hollandaise, meringues, egg pasta, cake batters, pastry glazes on buns/brioche, meatballs/burgers (binder).',
        contaminationRisks_es: 'Pinceles de pastelería, batidoras varilla compartidas, planchas donde se hacen tortillas o hamburguesas con huevo.',
        contaminationRisks_en: 'Pastry egg-wash brushes, shared whisk mixers, griddle tops used for fried eggs/omelettes.',
        keywords: ['huevo', 'huevos', 'egg', 'eggs', 'mayonesa', 'mayonnaise', 'yema', 'clara', 'holandesa', 'hollandaise', 'merengue', 'brioche']
    },
    {
        id: 'fish',
        name_es: 'Pescado',
        name_en: 'Fish',
        icon: 'set_meal',
        color: '#0284C7',
        bg: '#E0F2FE',
        border: '#BAE6FD',
        whereItHides_es: 'Salsa Worcestershire (Lea & Perrins contiene anchoas), aderezo de ensalada César, salsa de pescado asiática (nam pla), gelatinas, caldos concentrados.',
        whereItHides_en: 'Worcestershire sauce (Lea & Perrins has anchovies), Caesar salad dressing, Asian fish sauce (nam pla), fish gelatin, stocks.',
        contaminationRisks_es: 'Tablas de corte de pescadería, aceites de fritura, planchas de marcado rápido de carnes y pescados.',
        contaminationRisks_en: 'Fish cutting boards, deep fryer oil, flat-top grills used for both meats and fish.',
        keywords: ['pescado', 'fish', 'anchoa', 'anchoas', 'anchovy', 'anchovies', 'atun', 'tuna', 'salmon', 'worcestershire', 'cesar', 'caesar', 'nam pla', 'fumet', 'bacalao', 'cod', 'merluza']
    },
    {
        id: 'lupin',
        name_es: 'Altramuces',
        name_en: 'Lupin',
        icon: 'local_florist',
        color: '#9333EA',
        bg: '#F3E8FF',
        border: '#E9D5FF',
        whereItHides_es: 'Harina de altramuz en panes artesanales europeos, masas de pizza rústicas, tartas y productos de panadería vegana o sin gluten.',
        whereItHides_en: 'Lupin flour used in artisan European breads, pizza dough, vegan bakery items, specialty gluten-free baked goods.',
        contaminationRisks_es: 'Harinas volátiles en obradores de panadería, contenedores de harina compartidos.',
        contaminationRisks_en: 'Airborne flour in bakery prep rooms, shared bulk flour bins.',
        keywords: ['altramuz', 'altramuces', 'lupin', 'harina de altramuz', 'lupine']
    },
    {
        id: 'milk',
        name_es: 'Leche (Lácteos)',
        name_en: 'Milk',
        icon: 'water_drop',
        color: '#2563EB',
        bg: '#EFF6FF',
        border: '#BFDBFE',
        whereItHides_es: 'Mantequilla, queso, nata (crema de leche), yogur, suero lácteo (whey), leche en polvo en panes de molde, bechamel, chocolate con leche, purés.',
        whereItHides_en: 'Butter, cheese, double/single cream, yogurt, whey protein, milk powder in packaged breads, béchamel, milk chocolate, mashed potatoes.',
        contaminationRisks_es: 'Espumadores de vapor de cafeteras, cucharas para servir purés con mantequilla, recipientes de postres no esterilizados.',
        contaminationRisks_en: 'Coffee machine steam wands, serving spoons for buttered mash, shared dessert cookware.',
        keywords: ['leche', 'milk', 'mantequilla', 'butter', 'queso', 'cheese', 'nata', 'cream', 'yogur', 'yogurt', 'suero', 'whey', 'parmesano', 'cheddar', 'mozzarella', 'lacteo', 'dairy']
    },
    {
        id: 'molluscs',
        name_es: 'Moluscos',
        name_en: 'Molluscs',
        icon: 'water',
        color: '#0D9488',
        bg: '#CCFBF1',
        border: '#99F6E4',
        whereItHides_es: 'Mejillones, almejas, calamares, pulpo, ostras, salsa de ostras (Oyster sauce típica en salteados chinos), paellas marineras, caldos.',
        whereItHides_en: 'Mussels, clams, squid, calamari, octopus, oysters, oyster sauce (common in Chinese stir-fries), seafood stews/chowder.',
        contaminationRisks_es: 'Agua de cocción de mariscos compartida, woks donde se salteó con salsa de ostras, cucharas de degustación.',
        contaminationRisks_en: 'Shared pasta/seafood boiling water, woks coated with oyster sauce residues, tasting spoons.',
        keywords: ['mejillon', 'mejillones', 'mussel', 'mussels', 'calamar', 'calamares', 'squid', 'calamari', 'pulpo', 'octopus', 'ostra', 'ostras', 'oyster', 'oyster sauce', 'almeja', 'almejas', 'clam', 'clams']
    },
    {
        id: 'mustard',
        name_es: 'Mostaza',
        name_en: 'Mustard',
        icon: 'grain',
        color: '#EAB308',
        bg: '#FEFCE8',
        border: '#FEF08A',
        whereItHides_es: 'Mostaza Dijon, inglesa o en grano, vinagretas de ensalada, mayonesas compuestas, marinadas de asados, mezclas de curry en polvo.',
        whereItHides_en: 'Dijon, English or wholegrain mustard, salad dressings, compound mayonnaises, barbecue marinades, curry powders.',
        contaminationRisks_es: 'Biberones de salsas compartidos, espátulas de hamburguesas, recipientes de aderezos abiertos en línea fría.',
        contaminationRisks_en: 'Squeeze sauce bottles, burger turnaround spatulas, open dressing pans on cold lines.',
        keywords: ['mostaza', 'mustard', 'dijon', 'mostaza en grano', 'wholegrain mustard']
    },
    {
        id: 'peanuts',
        name_es: 'Cacahuetes (Maní)',
        name_en: 'Peanuts',
        icon: 'nutrition',
        color: '#B45309',
        bg: '#FEF3C7',
        border: '#FDE68A',
        whereItHides_es: 'Mantequilla de cacahuete, aceite de cacahuete, salsa Satay, currys del sudeste asiático, barritas energéticas, coberturas crujientes.',
        whereItHides_en: 'Peanut butter, peanut/groundnut oil, Satay sauce, Pad Thai, cereal bars, satay marinades, crunchy garnishes.',
        contaminationRisks_es: 'Cuchillos para untar mantequillas, tablas de corte de repostería, aceite para freír frutos secos.',
        contaminationRisks_en: 'Spread knives, pastry prep boards, oil vats used for nut frying.',
        keywords: ['cacahuete', 'cacahuetes', 'peanut', 'peanuts', 'mani', 'mantequilla de cacahuete', 'peanut butter', 'satay']
    },
    {
        id: 'sesame',
        name_es: 'Sésamo (Ajonjolí)',
        name_en: 'Sesame',
        icon: 'scatter_plot',
        color: '#78716C',
        bg: '#F5F5F4',
        border: '#E7E5E4',
        whereItHides_es: 'Tahini (ingrediente esencial del hummus y baba ganoush), aceite de sésamo en salteados, panes de hamburguesa con semillas, sushi, gomashio.',
        whereItHides_en: 'Tahini (in hummus and baba ganoush), sesame oil in stir-fries, sesame-topped burger buns, sushi rolls, gomashio seasoning.',
        contaminationRisks_es: 'Semillas sueltas que se dispersan en mesas de trabajo y planchas, tostadores donde caen semillas al fondo.',
        contaminationRisks_en: 'Loose seeds easily bouncing across prep benches and griddles, seed residue in bun toasters.',
        keywords: ['sesamo', 'sesame', 'tahini', 'tahina', 'hummus', 'ajonjoli', 'aceite de sesamo', 'sesame oil']
    },
    {
        id: 'soya',
        name_es: 'Soja',
        name_en: 'Soya',
        icon: 'eco',
        color: '#16A34A',
        bg: '#DCFCE7',
        border: '#BBF7D0',
        whereItHides_es: 'Salsa de soja, salsa teriyaki, tofu, edamame, miso, proteína vegetal texturizada (hamburguesas veganas), lecitina de soja (chocolates, panes industriales).',
        whereItHides_en: 'Soy sauce, teriyaki sauce, tofu, edamame, miso, textured vegetable protein, soya lecithin (emulsifier in chocolates and breads).',
        contaminationRisks_es: 'Woks y sartenes donde se salteó con salsa de soja, botellas dosificadoras de salsa, planchas.',
        contaminationRisks_en: 'Woks coated with soy sauce glazes, squeeze bottles, flat-top grills.',
        keywords: ['soja', 'soya', 'soy', 'soy sauce', 'tofu', 'edamame', 'miso', 'teriyaki', 'lecitina de soja', 'tamari']
    },
    {
        id: 'sulphites',
        name_es: 'Sulfitos',
        name_en: 'Sulphites',
        icon: 'science',
        color: '#9F1239',
        bg: '#FFE4E6',
        border: '#FECDD3',
        whereItHides_es: 'Vinos (tinto y blanco usados para reducciones y guisos), vinagres de vino, sidra, frutos secos deshidratados (pasas, orejones, dátiles), carnes procesadas/salchichas.',
        whereItHides_en: 'Wine (red/white in cooking reductions), wine vinegars, cider, dried fruits (raisins, dried apricots), processed burgers and sausages (preservative E220-E228).',
        contaminationRisks_es: 'Ollas y cazuelas donde se desglasó con vino, tablas donde se picaron pasas o frutas secas sulfuradas.',
        contaminationRisks_en: 'Pans deglazed with cooking wine, boards where dried sulphured fruits were chopped.',
        keywords: ['vino', 'wine', 'sulfito', 'sulfitos', 'sulphite', 'sulphites', 'pasas', 'raisins', 'orejones', 'sidra', 'cider', 'vinagre de vino']
    },
    {
        id: 'nuts',
        name_es: 'Frutos Secos (Cáscara)',
        name_en: 'Tree Nuts',
        icon: 'nature',
        color: '#7C2D12',
        bg: '#FFEDD5',
        border: '#FED7AA',
        whereItHides_es: 'Pesto tradicional (piñones o nueces), mazapán, praliné, harina de almendra (macarons, tartas), nueces en ensaladas, leches vegetales de almendra/avellana.',
        whereItHides_en: 'Traditional pesto (pine nuts/walnuts), marzipan, praline, almond flour (macarons, cakes), nuts in salads, almond/cashew plant milks.',
        contaminationRisks_es: 'Picadoras y robots de cocina (Thermomix, procesadores) no lavados a fondo, mangas pasteleras, tablas de repostería.',
        contaminationRisks_en: 'Food processors (Thermomix, blenders) not sanitized, piping bags, bakery cutting boards.',
        keywords: ['nuez', 'nueces', 'walnut', 'walnuts', 'almendra', 'almendras', 'almond', 'almonds', 'avellana', 'avellanas', 'hazelnut', 'hazelnuts', 'pistacho', 'pistachos', 'pistachio', 'pistachios', 'anacardo', 'anacardos', 'cashew', 'cashews', 'pinon', 'pinones', 'pine nuts', 'pesto', 'pecana', 'pecans', 'macadamia']
    }
];

/**
 * Analizador automático de recetas
 * Examina los ingredientes de una receta y devuelve la lista de alérgenos detectados
 */

/**
 * Analizador oficial de alérgenos y contaminación cruzada de recetas y platos.
 * Detecta alérgenos directos (X) basándose en la ficha técnica, etiquetas manuales o escaneo de ingredientes.
 */
window.detectRecipeAllergens = function(recipe) {
    if (!recipe) return [];
    
    // Si el plato tiene alérgenos declarados directamente
    if (recipe.allergens && Array.isArray(recipe.allergens)) {
        return Array.from(new Set(recipe.allergens));
    }
    if (recipe.contains && Array.isArray(recipe.contains)) {
        return Array.from(new Set(recipe.contains));
    }

    // Si tiene etiquetas manuales guardadas en tags (ej: "allergen:gluten")
    const manualAllergens = [];
    if (recipe.tags && Array.isArray(recipe.tags)) {
        recipe.tags.forEach(tag => {
            if (typeof tag === 'string' && tag.startsWith('allergen:')) {
                const id = tag.replace('allergen:', '').trim().toLowerCase();
                if (window.UK_ALLERGENS && window.UK_ALLERGENS.some(a => a.id === id)) {
                    manualAllergens.push(id);
                }
            }
        });
    }
    if (manualAllergens.length > 0) {
        return Array.from(new Set(manualAllergens));
    }

    // Escaneo automático sobre los ingredientes y nombre
    const detected = new Set();
    const textsToScan = [];
    
    if (recipe.name_es) textsToScan.push(recipe.name_es.toLowerCase());
    if (recipe.name_en) textsToScan.push(recipe.name_en.toLowerCase());
    if (recipe.name) textsToScan.push(recipe.name.toLowerCase());
    if (recipe.rawName) textsToScan.push(recipe.rawName.toLowerCase());
    if (recipe.description_es) textsToScan.push(recipe.description_es.toLowerCase());
    if (recipe.description_en) textsToScan.push(recipe.description_en.toLowerCase());

    if (Array.isArray(recipe.ingredients)) {
        recipe.ingredients.forEach(ing => {
            if (typeof ing === 'string') {
                textsToScan.push(ing.toLowerCase());
            } else if (ing && typeof ing === 'object') {
                if (ing.name_es) textsToScan.push(ing.name_es.toLowerCase());
                if (ing.name_en) textsToScan.push(ing.name_en.toLowerCase());
                if (ing.name) textsToScan.push(ing.name.toLowerCase());
            }
        });
    }

    const fullContent = textsToScan.join(' ');

    if (window.UK_ALLERGENS) {
        window.UK_ALLERGENS.forEach(allergen => {
            const found = allergen.keywords && allergen.keywords.some(kw => {
                const escaped = kw.replace(/[.*+?^${}()|[]\]/g, '\\$&');
                const regex = new RegExp('(^|[^a-záéíóúñ])' + escaped + '([^a-záéíóúñ]|$)', 'i');
                return regex.test(fullContent);
            });
            if (found) {
                detected.add(allergen.id);
            }
        });
    }

    return Array.from(detected);
};

/**
 * Detector de riesgo de contaminación cruzada (O)
 * Utilizado por la Matriz Oficial de Stanley's y por recetas etiquetadas con 'cross:gluten'
 */
window.detectRecipeCrossContamination = function(recipe) {
    if (!recipe) return [];
    if (recipe.crossContamination && Array.isArray(recipe.crossContamination)) {
        return Array.from(new Set(recipe.crossContamination));
    }
    const manualCC = [];
    if (recipe.tags && Array.isArray(recipe.tags)) {
        recipe.tags.forEach(tag => {
            if (typeof tag === 'string' && tag.startsWith('cross:')) {
                const id = tag.replace('cross:', '').trim().toLowerCase();
                if (window.UK_ALLERGENS && window.UK_ALLERGENS.some(a => a.id === id)) {
                    manualCC.push(id);
                }
            }
        });
    }
    return manualCC;
};


/**
 * STANLEY'S SW16 STREATHAM - OFFICIAL ALLERGEN MATRIX
 * Extracted directly from restaurant document: STANLEYS UPDATED ALLERGENS 05_26.numbers
 * Total 73 dishes across 8 sections with FSA UK 14 Allergens compliance.
 * Key: X = Allergen present | O = Cross-contamination risk
 */
window.STANLEYS_OFFICIAL_ALLERGENS = [
    {
        id: "stanley_01",
        section: "FINGER FOOD",
        rawName: "NASHV. FRIED CHICKEN",
        name_en: "Nashville Fried Chicken",
        name_es: "Pollo frito estilo Nashville",
        name: "Nashville Fried Chicken",
        allergens: ["gluten", "milk"],
        crossContamination: ["eggs"],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "O", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_02",
        section: "FINGER FOOD",
        rawName: "NACHOS TO SHARE",
        name_en: "Nachos to Share",
        name_es: "Nachos para compartir",
        name: "Nachos to Share",
        allergens: ["gluten", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_03",
        section: "FINGER FOOD",
        rawName: "STARTER RIBS",
        name_en: "Starter Ribs",
        name_es: "Costillitas de cerdo (Entrante)",
        name: "Starter Ribs",
        allergens: ["gluten", "soya", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Soya": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:soya', 'allergen:sulphites'],
    },
    {
        id: "stanley_04",
        section: "FINGER FOOD",
        rawName: "CHIX WINGS BBQ",
        name_en: "Chicken Wings BBQ",
        name_es: "Alitas de pollo BBQ",
        name: "Chicken Wings BBQ",
        allergens: ["celery", "gluten", "milk", "soya"],
        crossContamination: ["eggs"],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "O", "Milk": "X", "Soya": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:milk', 'allergen:soya'],
    },
    {
        id: "stanley_05",
        section: "FINGER FOOD",
        rawName: "CHIX WINGS BUFFALO",
        name_en: "Chicken Wings Buffalo",
        name_es: "Alitas de pollo Buffalo",
        name: "Chicken Wings Buffalo",
        allergens: ["celery", "milk"],
        crossContamination: ["gluten", "eggs", "molluscs", "mustard"],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "O", "Eggs": "O", "Milk": "X", "Mollusc": "O", "Mustard": "O"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:milk'],
    },
    {
        id: "stanley_06",
        section: "FINGER FOOD",
        rawName: "CHIX WINGS PERI PERI",
        name_en: "Chicken Wings Peri Peri",
        name_es: "Alitas de pollo Peri Peri",
        name: "Chicken Wings Peri Peri",
        allergens: [],
        crossContamination: ["gluten"],
        rawAllergens: {"Cereals containing gluten": "O"},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_07",
        section: "FINGER FOOD",
        rawName: "CHIX WINGS KOREAN",
        name_en: "Chicken Wings Korean",
        name_es: "Alitas de pollo estilo coreano",
        name: "Chicken Wings Korean",
        allergens: [],
        crossContamination: ["gluten"],
        rawAllergens: {"Cereals containing gluten": "O"},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_08",
        section: "FINGER FOOD",
        rawName: "VEGAN CHICK\u2019N TENDERS",
        name_en: "VEGAN CHICK\u2019N TENDERS",
        name_es: "VEGAN CHICK\u2019N TENDERS",
        name: "VEGAN CHICK\u2019N TENDERS",
        allergens: ["gluten"],
        crossContamination: ["soya"],
        rawAllergens: {"Cereals containing gluten": "X", "Soya": "O"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten'],
    },
    {
        id: "stanley_09",
        section: "FINGER FOOD",
        rawName: "CALAMARI & COURGETTE",
        name_en: "Calamari & Courgette",
        name_es: "Calamares y calabac\u00edn fritos",
        name: "Calamari & Courgette",
        allergens: ["gluten", "eggs", "milk", "molluscs", "mustard", "sulphites"],
        crossContamination: ["fish"],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Fish": "O", "Milk": "X", "Mollusc": "X", "Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:molluscs', 'allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_10",
        section: "FINGER FOOD",
        rawName: "MOZZARELLA STICKS",
        name_en: "Mozzarella Sticks",
        name_es: "Palitos de mozzarella",
        name: "Mozzarella Sticks",
        allergens: ["gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_11",
        section: "FINGER FOOD",
        rawName: "GARLIC BREAD",
        name_en: "Garlic Bread",
        name_es: "Pan de ajo",
        name: "Garlic Bread",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_12",
        section: "MAINS",
        rawName: "HALF \\ FULL RIBS & CHIPS",
        name_en: "Half / Full Ribs & Chips",
        name_es: "Costillas de cerdo (Media / Entera) con patatas",
        name: "Half / Full Ribs & Chips",
        allergens: ["gluten", "soya", "sulphites"],
        crossContamination: ["eggs", "milk"],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "O", "Milk": "O", "Soya": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:soya', 'allergen:sulphites'],
    },
    {
        id: "stanley_13",
        section: "MAINS",
        rawName: "SIRLOIN STEAK & CHIPS",
        name_en: "Sirloin Steak & Chips",
        name_es: "Filete de lomo de ternera (Sirloin) con patatas",
        name: "Sirloin Steak & Chips",
        allergens: ["mustard", "sulphites"],
        crossContamination: ["milk"],
        rawAllergens: {"Milk": "O", "Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_14",
        section: "MAINS",
        rawName: "FISH & CHIPS",
        name_en: "Fish & Chips",
        name_es: "Pescado frito con patatas tradicional",
        name: "Fish & Chips",
        allergens: ["gluten", "eggs", "milk", "mustard", "sulphites"],
        crossContamination: ["molluscs"],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Mollusc": "O", "Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_15",
        section: "MAINS",
        rawName: "1/2 CHICKEN & CHIPS",
        name_en: "1/2 Chicken & Chips",
        name_es: "Medio pollo asado con patatas",
        name: "1/2 Chicken & Chips",
        allergens: ["mustard"],
        crossContamination: [],
        rawAllergens: {"Mustard": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:mustard'],
    },
    {
        id: "stanley_16",
        section: "MAINS",
        rawName: "CHEESE BURGER & CHIPS",
        name_en: "Cheese Burger & Chips",
        name_es: "Hamburguesa con queso y patatas",
        name: "Cheese Burger & Chips",
        allergens: ["gluten", "eggs", "milk", "mustard", "sesame", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Mustard": "X", "Sesame seeds": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:sesame', 'allergen:sulphites'],
    },
    {
        id: "stanley_17",
        section: "MAINS",
        rawName: "VEGGIE BURGER & CHIPS",
        name_en: "Veggie Burger & Chips",
        name_es: "Hamburguesa vegetariana y patatas",
        name: "Veggie Burger & Chips",
        allergens: ["gluten", "eggs", "milk", "mustard", "nuts", "sesame", "soya", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Mustard": "X", "Nuts": "X", "Sesame seeds": "X", "Soya": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:nuts', 'allergen:sesame', 'allergen:soya', 'allergen:sulphites'],
    },
    {
        id: "stanley_18",
        section: "MAINS",
        rawName: "VEGAN BURGER & CHIPS",
        name_en: "Vegan Burger & Chips",
        name_es: "Hamburguesa vegana y patatas",
        name: "Vegan Burger & Chips",
        allergens: ["gluten", "mustard", "nuts", "sesame", "soya", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Mustard": "X", "Nuts": "X", "Sesame seeds": "X", "Soya": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:mustard', 'allergen:nuts', 'allergen:sesame', 'allergen:soya', 'allergen:sulphites'],
    },
    {
        id: "stanley_19",
        section: "MAINS",
        rawName: "BUFFALO CHICKEN BURGER",
        name_en: "Buffalo Chicken Burger",
        name_es: "Hamburguesa de pollo Buffalo",
        name: "Buffalo Chicken Burger",
        allergens: ["celery", "gluten", "eggs", "milk", "mustard", "sesame", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Mustard": "X", "Sesame seeds": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:sesame', 'allergen:sulphites'],
    },
    {
        id: "stanley_20",
        section: "MAINS",
        rawName: "PIE OF THE DAY & GREENS",
        name_en: "Pie of the Day & Greens",
        name_es: "Pastel del d\u00eda con verduras",
        name: "Pie of the Day & Greens",
        allergens: ["celery", "gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_21",
        section: "MAINS",
        rawName: "*BACON",
        name_en: "*Bacon (Extra)",
        name_es: "*Bacon / Tocino extra",
        name: "*Bacon (Extra)",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_22",
        section: "MAINS",
        rawName: "*CURRY SAUCE",
        name_en: "*Curry Sauce",
        name_es: "*Salsa al curry",
        name: "*Curry Sauce",
        allergens: ["milk"],
        crossContamination: [],
        rawAllergens: {"Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:milk'],
    },
    {
        id: "stanley_23",
        section: "MAINS",
        rawName: "*BONE MARROW GRAVY",
        name_en: "*Bone Marrow Gravy",
        name_es: "*Gravy de tu\u00e9tano",
        name: "*Bone Marrow Gravy",
        allergens: ["celery", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:sulphites'],
    },
    {
        id: "stanley_24",
        section: "MAINS",
        rawName: "*PEPPERCOARN SAUCE",
        name_en: "*Peppercorn Sauce",
        name_es: "*Salsa a la pimienta verde",
        name: "*Peppercorn Sauce",
        allergens: ["celery", "milk", "mustard", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Milk": "X", "Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:milk', 'allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_25",
        section: "MAINS",
        rawName: "*HERB & GARLIC BUTTER",
        name_en: "*Herb & Garlic Butter",
        name_es: "*Mantequilla de ajo y hierbas",
        name: "*Herb & Garlic Butter",
        allergens: ["milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_26",
        section: "FLAT BREADS",
        rawName: "CHEESY GARLIC BREAD",
        name_en: "Cheesy Garlic Bread",
        name_es: "Pan de ajo con queso fundido",
        name: "Cheesy Garlic Bread",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_27",
        section: "FLAT BREADS",
        rawName: "CHEESE & ANCHOVIES",
        name_en: "Cheese & Anchovies Flatbread",
        name_es: "Pan plano con queso y anchoas",
        name: "Cheese & Anchovies Flatbread",
        allergens: ["gluten", "fish", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Fish": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:fish', 'allergen:milk'],
    },
    {
        id: "stanley_28",
        section: "FLAT BREADS",
        rawName: "CHEESE, TOMATOES & PESTO",
        name_en: "Cheese, Tomatoes & Pesto Flatbread",
        name_es: "Pan plano con queso, tomate y pesto",
        name: "Cheese, Tomatoes & Pesto Flatbread",
        allergens: ["gluten", "milk", "nuts"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X", "Nuts": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk', 'allergen:nuts'],
    },
    {
        id: "stanley_29",
        section: "FLAT BREADS",
        rawName: "HAM, CHEESE & GARLIC",
        name_en: "Ham, Cheese & Garlic Flatbread",
        name_es: "Pan plano de jam\u00f3n, queso y ajo",
        name: "Ham, Cheese & Garlic Flatbread",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_30",
        section: "FLAT BREADS",
        rawName: "MORTADELLA, CHEESE & PISTACHIO",
        name_en: "Mortadella, Cheese & Pistachio Flatbread",
        name_es: "Pan plano de mortadela, queso y pistacho",
        name: "Mortadella, Cheese & Pistachio Flatbread",
        allergens: ["gluten", "milk", "nuts"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X", "Nuts": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk', 'allergen:nuts'],
    },
    {
        id: "stanley_31",
        section: "SOS PIZZA",
        rawName: "MARGHERITA",
        name_en: "Pizza Margherita",
        name_es: "Pizza Margarita",
        name: "Pizza Margherita",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_32",
        section: "SOS PIZZA",
        rawName: "VEGAN MARGHERITA",
        name_en: "Vegan Margherita Pizza",
        name_es: "Pizza Margarita Vegana",
        name: "Vegan Margherita Pizza",
        allergens: ["gluten"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten'],
    },
    {
        id: "stanley_33",
        section: "SOS PIZZA",
        rawName: "AUBERGINE",
        name_en: "Aubergine Pizza",
        name_es: "Pizza de berenjena",
        name: "Aubergine Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_34",
        section: "SOS PIZZA",
        rawName: "AMERICAN HOT",
        name_en: "American Hot Pizza",
        name_es: "Pizza American Hot (Picante)",
        name: "American Hot Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_35",
        section: "SOS PIZZA",
        rawName: "PEPEPRONI",
        name_en: "Pepperoni Pizza",
        name_es: "Pizza de pepperoni",
        name: "Pepperoni Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_36",
        section: "SOS PIZZA",
        rawName: "WEIRDOUGH",
        name_en: "The Weirdough Pizza",
        name_es: "Pizza Weirdough",
        name: "The Weirdough Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_37",
        section: "SOS PIZZA",
        rawName: "ALLOTTMENT",
        name_en: "The Allotment Pizza",
        name_es: "Pizza The Allotment (Vegetales)",
        name: "The Allotment Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_38",
        section: "SOS PIZZA",
        rawName: "TRUFFLE PIG",
        name_en: "Truffle Pig Pizza",
        name_es: "Pizza Truffle Pig (Trufa y cerdo)",
        name: "Truffle Pig Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_39",
        section: "SOS PIZZA",
        rawName: "GF BASE",
        name_en: "Gluten-Free Pizza Base",
        name_es: "Base de pizza sin gluten (GF)",
        name: "Gluten-Free Pizza Base",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_40",
        section: "SOS PIZZA",
        rawName: "*MOZZARELLA",
        name_en: "*Extra Mozzarella",
        name_es: "*Extra de queso mozzarella",
        name: "*Extra Mozzarella",
        allergens: ["milk"],
        crossContamination: [],
        rawAllergens: {"Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:milk'],
    },
    {
        id: "stanley_41",
        section: "SOS PIZZA",
        rawName: "*AUBERGINE",
        name_en: "*Extra Aubergine",
        name_es: "*Extra de berenjena",
        name: "*Extra Aubergine",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_42",
        section: "SOS PIZZA",
        rawName: "*COURGETTE",
        name_en: "*Extra Courgette",
        name_es: "*Extra de calabac\u00edn",
        name: "*Extra Courgette",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_43",
        section: "SOS PIZZA",
        rawName: "*ARTICHOKES",
        name_en: "*Extra Artichokes",
        name_es: "*Extra de alcachofas",
        name: "*Extra Artichokes",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_44",
        section: "SOS PIZZA",
        rawName: "*PEPPERONI",
        name_en: "*Extra Pepperoni",
        name_es: "*Extra de pepperoni",
        name: "*Extra Pepperoni",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_45",
        section: "SOS PIZZA",
        rawName: "*N\u2019DUJA",
        name_en: "*N\u2019DUJA",
        name_es: "*N\u2019DUJA",
        name: "*N\u2019DUJA",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_46",
        section: "SOS PIZZA",
        rawName: "*JELAPENOS",
        name_en: "*Extra Jalape\u00f1os",
        name_es: "*Extra de jalape\u00f1os",
        name: "*Extra Jalape\u00f1os",
        allergens: ["sulphites"],
        crossContamination: [],
        rawAllergens: {"Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:sulphites'],
    },
    {
        id: "stanley_47",
        section: "SOS PIZZA",
        rawName: "*MUSHROOMS",
        name_en: "*Extra Mushrooms",
        name_es: "*Extra de champi\u00f1ones",
        name: "*Extra Mushrooms",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_48",
        section: "SOS PIZZA",
        rawName: "*ONIONS",
        name_en: "*Extra Onions",
        name_es: "*Extra de cebolla",
        name: "*Extra Onions",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_49",
        section: "SOS PIZZA",
        rawName: "*HAM",
        name_en: "*Extra Ham",
        name_es: "*Extra de jam\u00f3n",
        name: "*Extra Ham",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_50",
        section: "SOS PIZZA",
        rawName: "*PANCETTA",
        name_en: "*Extra Pancetta",
        name_es: "*Extra de panceta italiana",
        name: "*Extra Pancetta",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_51",
        section: "SOS PIZZA",
        rawName: "*TRUFFLE OIL",
        name_en: "*Truffle Oil Drizzle",
        name_es: "*Chorro de aceite de trufa",
        name: "*Truffle Oil Drizzle",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_52",
        section: "SOS PIZZA",
        rawName: "SPICY HONEY",
        name_en: "Spicy Hot Honey",
        name_es: "Miel picante Hot Honey",
        name: "Spicy Hot Honey",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_53",
        section: "SOS PIZZA",
        rawName: "SRIRACHA MAYO",
        name_en: "Sriracha Mayo Dip",
        name_es: "Salsa mayonesa Sriracha",
        name: "Sriracha Mayo Dip",
        allergens: ["eggs", "milk", "mustard", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Eggs": "X", "Milk": "X", "Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_54",
        section: "SOS PIZZA",
        rawName: "BASIL PESTO AIOLI",
        name_en: "Basil Pesto Aioli Dip",
        name_es: "Salsa alioli de pesto de albahaca",
        name: "Basil Pesto Aioli Dip",
        allergens: ["eggs", "milk", "mustard", "nuts", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Eggs": "X", "Milk": "X", "Mustard": "X", "Nuts": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:eggs', 'allergen:milk', 'allergen:mustard', 'allergen:nuts', 'allergen:sulphites'],
    },
    {
        id: "stanley_55",
        section: "SIDES",
        rawName: "TRIPLE COOKED CHIPS",
        name_en: "Triple Cooked Chips",
        name_es: "Patatas fritas caseras tres cocciones",
        name: "Triple Cooked Chips",
        allergens: [],
        crossContamination: ["gluten", "eggs", "milk", "molluscs"],
        rawAllergens: {"Cereals containing gluten": "O", "Eggs": "O", "Milk": "O", "Mollusc": "O"},
        is_demo: false,
        is_official: true,
        tags: [],
    },
    {
        id: "stanley_56",
        section: "SIDES",
        rawName: "MIXED LEAF SALAD",
        name_en: "Mixed Leaf Salad",
        name_es: "Ensalada de hojas verdes mixtas",
        name: "Mixed Leaf Salad",
        allergens: ["mustard", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_57",
        section: "SIDES",
        rawName: "BUTTERED GREEN BEANS",
        name_en: "Buttered Green Beans",
        name_es: "Jud\u00edas verdes salteadas a la mantequilla",
        name: "Buttered Green Beans",
        allergens: ["milk"],
        crossContamination: [],
        rawAllergens: {"Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:milk'],
    },
    {
        id: "stanley_58",
        section: "SIDES",
        rawName: "TOMATO & ONION SALAD",
        name_en: "Tomato & Onion Salad",
        name_es: "Ensalada de tomate y cebolla",
        name: "Tomato & Onion Salad",
        allergens: ["mustard", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Mustard": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:mustard', 'allergen:sulphites'],
    },
    {
        id: "stanley_59",
        section: "KIDS MENU",
        rawName: "KIDS TENDERS + CHIPS",
        name_en: "Kids Chicken Tenders & Chips",
        name_es: "Men\u00fa infantil: Tiras de pollo con patatas",
        name: "Kids Chicken Tenders & Chips",
        allergens: ["gluten", "eggs", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk'],
    },
    {
        id: "stanley_60",
        section: "KIDS MENU",
        rawName: "KIDS MARGHERITA",
        name_en: "Kids Margherita Pizza",
        name_es: "Men\u00fa infantil: Pizza Margarita",
        name: "Kids Margherita Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_61",
        section: "KIDS MENU",
        rawName: "KIDS HAM MARGHERITA",
        name_en: "Kids Ham Margherita Pizza",
        name_es: "Men\u00fa infantil: Pizza Margarita con jam\u00f3n",
        name: "Kids Ham Margherita Pizza",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_62",
        section: "SUNDAY ROAST",
        rawName: "BEEF",
        name_en: "Sunday Roast: British Roast Beef",
        name_es: "Sunday Roast: Ternera asada brit\u00e1nica",
        name: "Sunday Roast: British Roast Beef",
        allergens: ["celery", "gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_63",
        section: "SUNDAY ROAST",
        rawName: "LAMB",
        name_en: "Sunday Roast: Roast Lamb",
        name_es: "Sunday Roast: Cordero asado",
        name: "Sunday Roast: Roast Lamb",
        allergens: ["celery", "gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_64",
        section: "SUNDAY ROAST",
        rawName: "PORK",
        name_en: "Sunday Roast: Roast Pork Belly & Crackling",
        name_es: "Sunday Roast: Panceta de cerdo crujiente",
        name: "Sunday Roast: Roast Pork Belly & Crackling",
        allergens: ["celery", "gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_65",
        section: "SUNDAY ROAST",
        rawName: "CHICKEN",
        name_en: "Sunday Roast: Roast Half Chicken",
        name_es: "Sunday Roast: Medio pollo asado",
        name: "Sunday Roast: Roast Half Chicken",
        allergens: ["celery", "gluten", "eggs", "milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Eggs": "X", "Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:eggs', 'allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_66",
        section: "SUNDAY ROAST",
        rawName: "VEG ROAST",
        name_en: "Sunday Roast: Nut & Mushroom Roast (Veg)",
        name_es: "Sunday Roast: Asado vegetariano de frutos secos",
        name: "Sunday Roast: Nut & Mushroom Roast (Veg)",
        allergens: ["celery", "gluten", "nuts", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Celery": "X", "Cereals containing gluten": "X", "Nuts": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:celery', 'allergen:gluten', 'allergen:nuts', 'allergen:sulphites'],
    },
    {
        id: "stanley_67",
        section: "SUNDAY ROAST",
        rawName: "LEEKS GRATINE",
        name_en: "Sunday Roast Side: Leek Gratin",
        name_es: "Acompa\u00f1amiento: Puerros gratinados a la crema",
        name: "Sunday Roast Side: Leek Gratin",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_68",
        section: "SUNDAY ROAST",
        rawName: "BUTTERED GREENS",
        name_en: "Sunday Roast Side: Buttered Greens",
        name_es: "Acompa\u00f1amiento: Verduras salteadas a la mantequilla",
        name: "Sunday Roast Side: Buttered Greens",
        allergens: ["milk", "sulphites"],
        crossContamination: [],
        rawAllergens: {"Milk": "X", "Sulphur dioxide": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:milk', 'allergen:sulphites'],
    },
    {
        id: "stanley_69",
        section: "DESSERTS",
        rawName: "STICKY TOFFE",
        name_en: "Sticky Toffee Pudding",
        name_es: "Pudin de caramelo y d\u00e1tiles (Sticky Toffee)",
        name: "Sticky Toffee Pudding",
        allergens: ["gluten", "eggs", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Eggs": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:eggs', 'allergen:milk'],
    },
    {
        id: "stanley_70",
        section: "DESSERTS",
        rawName: "BLUBERRYS  PANNACOTTA & CRUMB",
        name_en: "Blueberry Panna Cotta & Crumb",
        name_es: "Panacota de ar\u00e1ndanos con crumble",
        name: "Blueberry Panna Cotta & Crumb",
        allergens: ["gluten", "milk"],
        crossContamination: [],
        rawAllergens: {"Cereals containing gluten": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:gluten', 'allergen:milk'],
    },
    {
        id: "stanley_71",
        section: "DESSERTS",
        rawName: "VANILLA ICE CREAM",
        name_en: "Vanilla Ice Cream",
        name_es: "Helado de vainilla",
        name: "Vanilla Ice Cream",
        allergens: ["eggs", "milk"],
        crossContamination: [],
        rawAllergens: {"Eggs": "X", "Milk": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:eggs', 'allergen:milk'],
    },
    {
        id: "stanley_72",
        section: "DESSERTS",
        rawName: "CHOCOLATE ICE CREAM",
        name_en: "Chocolate Ice Cream",
        name_es: "Helado de chocolate",
        name: "Chocolate Ice Cream",
        allergens: ["eggs", "milk", "soya"],
        crossContamination: ["nuts"],
        rawAllergens: {"Eggs": "X", "Milk": "X", "Nuts": "O", "Soya": "X"},
        is_demo: false,
        is_official: true,
        tags: ['allergen:eggs', 'allergen:milk', 'allergen:soya'],
    },
    {
        id: "stanley_73",
        section: "DESSERTS",
        rawName: "LEMON SORBET",
        name_en: "Lemon Sorbet",
        name_es: "Sorbete de lim\u00f3n",
        name: "Lemon Sorbet",
        allergens: [],
        crossContamination: [],
        rawAllergens: {},
        is_demo: false,
        is_official: true,
        tags: [],
    },
];

// Alias DEMO_UK_RECIPES to the official Stanley's allergen dishes
window.DEMO_UK_RECIPES = window.STANLEYS_OFFICIAL_ALLERGENS;

/**
 * Fallback / Compatibilidad con demostraciones anteriores
 */
window.DEMO_UK_RECIPES = window.STANLEYS_OFFICIAL_ALLERGENS;

window.UK_DIETARY_PROFILES = [
    {
        id: 'celiac',
        name_es: 'Celíaco / Sin Gluten',
        name_en: 'Coeliac / Gluten-Free',
        icon: 'bakery_dining',
        color: '#D97706',
        allergens: ['gluten']
    },
    {
        id: 'lactose',
        name_es: 'Sin Lactosa / Lácteos',
        name_en: 'Lactose & Dairy-Free',
        icon: 'water_drop',
        color: '#2563EB',
        allergens: ['milk']
    },
    {
        id: 'nuts',
        name_es: 'Alergia a Frutos Secos y Maní',
        name_en: 'Nut Allergy (Peanuts & Tree Nuts)',
        icon: 'nutrition',
        color: '#EA580C',
        allergens: ['peanuts', 'nuts']
    },
    {
        id: 'seafood',
        name_es: 'Alergia al Marisco y Pescado',
        name_en: 'Seafood, Shellfish & Fish',
        icon: 'phishing',
        color: '#DC2626',
        allergens: ['crustaceans', 'molluscs', 'fish']
    },
    {
        id: 'vegan',
        name_es: 'Vegano Estricto',
        name_en: 'Strict Vegan Diet',
        icon: 'eco',
        color: '#059669',
        allergens: ['eggs', 'milk', 'fish', 'crustaceans', 'molluscs']
    },
    {
        id: 'eggs',
        name_es: 'Alérgico al Huevo',
        name_en: 'Egg-Free Diet',
        icon: 'egg',
        color: '#CA8A04',
        allergens: ['eggs']
    }
];
